### ISSUE TITLE
Range Filter UI improvement

### ISSUE THREAD

**Issue by IslandUsurper** [naymspace/backpex#363]
On the demo site, you can filter by the number of Likes a Post has. You can put in one or two numbers to be the endpoints of the range of Likes to show. But the fields don't say which is which, and if someone is unfamiliar, they may not even know _why_ there are two fields. Fortunately, the example links for "over 100" and "1–99" fill in the correct numbers so the behavior can be discovered that way.

Suggested labels:
- "From `[______]`"
  "To `[______]`"
- "Between `[_______]`"
  "and `[______]`"
- Inline the fields: "`[______]` to `[______]`"
- "`[______]` – `[_______]`"

**Comment by Flo0807** [comment]
Hey, thanks a lot for your feedback 🙏

What are your thoughts on using inline labels (see https://daisyui.com/components/input/#text-input-with-text-label-inside)?

![image](https://github.com/naymspace/backpex/assets/60519307/c70736b6-194c-4a0e-ad91-bba50543236f)

(@pehbehbeh)

**Comment by IslandUsurper** [comment]
Yeah, that would convey the intent very well.
