### ISSUE TITLE
Steps missing in installation guide?

### ISSUE THREAD

**Issue by rakso-startkoden** [naymspace/backpex#398]
Hi, I've been trying to add backpex to my project. Most things seems to work, but there is something with the styles that is not working properly. I also tried creating a fresh phoenix project (https://github.com/rakso-startkoden/backpex-test) and following in the steps, but its also not working 100% as expected.
In both cases there are no errors in consoles to give any clues as to what is wrong. Alpinejs is installed and tailwind config is updated as instructed.
Below are also some screenshots from my two attempts.

(From the fresh phoenix project)
![Screenshot from 2024-06-22 14-18-46](https://github.com/naymspace/backpex/assets/169435894/a1a97d11-c802-4a80-bf40-50856536f971)
![Screenshot from 2024-06-22 14-18-36](https://github.com/naymspace/backpex/assets/169435894/0cd22df6-178a-4caa-96bb-9310935718ee)

(From my already existing project)
![Screenshot from 2024-06-22 14-15-25](https://github.com/naymspace/backpex/assets/169435894/75cf9db2-dc49-4309-89f3-e353e0883139)

Thank you for a great project with lots of potential! I look forward to getting rid of my repetitive code for admin views.:)

**Comment by Flo0807** [comment]
Hey, thanks for your issue. I cloned your repo and fixed all the bugs related to Backpex installation. I created a pull request and explained why and what changes I made: https://github.com/rakso-startkoden/backpex-test/pull/1

This was very valuable feedback for us 🙏 I'll update the installation guide and cover the changes I made in the pull request so others won't run into the same problem installing Backpex. Thank you very much!

If you still have difficulties with Backpex in the future, do not hesitate to create a new issue or comment on this one. This is very helpful and will make the guides better and better.

@rakso-startkoden

**Comment by rakso-startkoden** [comment]
Thank you for the detailed instructions. It's now running in both my projects. In addition to the things you commented on the the test project. 
I would also suggest adding the following:
- A mention of alpinejs in https://github.com/naymspace/backpex/blob/develop/guides/get_started/prerequisites.md
- A mention of prerequisites on the https://github.com/naymspace/backpex/blob/develop/guides/get_started/installation.md. Now i missed that part of prerequisites because i jumped straight to the installation from the repo readme link.

Thanks again!

**Comment by Flo0807** [comment]
Hey, we have taken your feedback into account in the 0.5 release and improved the installation guide.

See [release notes](https://github.com/naymspace/backpex/releases/tag/0.5.0) and [upgrade guide](https://hexdocs.pm/backpex/v0-5.html).
