### ISSUE TITLE
Broken layout after following installation guide

### ISSUE THREAD

**Issue by lukaszsamson** [naymspace/backpex#417]
I created a new empty mix phoenix project, added backpex following installation guide. I apllied the fixes from https://github.com/naymspace/backpex/issues/399 and changed path in taliwind config to `../deps/backpex/**/*.*ex` as in https://github.com/rakso-startkoden/backpex-test/pull/1/files.

The app loads but the layout is broken. Notice logout button in the upper right corner

<img width="1471" alt="Screenshot 2024-06-27 at 05 22 24" src="https://github.com/naymspace/backpex/assets/1078186/e1d40597-9b90-40c5-8934-6c11f61a6ada">

**Comment by Flo0807** [comment]
It seems like you have not installed daisyUI correctly. How did you install it? Can you provide a `tailwind.config.js` or even the whole (demo) project?

**Comment by lukaszsamson** [comment]
I figured it out that I need to add it. The section https://github.com/naymspace/backpex/blob/develop/guides/get_started/installation.md#add-files-to-tailwind-content is not mentioning any changes besides adding `../deps/backpex/**/*.*ex`. It does not mention what nodejs deps are needed

**Comment by Flo0807** [comment]
> I figured it out that I need to add it. The section https://github.com/naymspace/backpex/blob/develop/guides/get_started/installation.md#add-files-to-tailwind-content is not mentioning any changes besides adding `../deps/backpex/**/*.*ex`. It does not mention what nodejs deps are needed

We have a [Prerequisites](https://hexdocs.pm/backpex/prerequisites.html) section that mentions daisyUI, but it's currently not linked in the installation guide. We will fix it with #403
