### ISSUE TITLE
Undefined function live_session/3

### ISSUE THREAD

**Issue by azharmalik3** [naymspace/backpex#422]
I am following the Backpex installation guide to run Backpex in my project.

But getting an error on adding the route.

![image](https://github.com/naymspace/backpex/assets/6176136/99fad084-cd0e-43d5-9008-33b2f3ed29b3)

![image](https://github.com/naymspace/backpex/assets/6176136/b156a5b1-ef80-401e-a287-07ce46df9767)

**Comment by Flo0807** [comment]
Hey, do you have a running Phoenix *LiveView* application? If you import `import Phoenix.LiveView.Router` it should work: https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.Router.html#live_session/3

**Comment by azharmalik3** [comment]
Yes, it works after import `LiveView.Router`.

Thanks.
