### ISSUE TITLE
Sidebar menu hidden by topbar in mobile

### ISSUE THREAD

**Issue by thomasfortes** [naymspace/backpex#428]
In the `app_shell` function the mobile menu has a z-index that puts the top of the menu below the topbar.

ps: It is a single char fix to put it below z-40 at: https://github.com/naymspace/backpex/blob/7c5672a4f1f89201838948a7d0c10c74d6e92238/lib/backpex/html/layout.ex#L79 
and I can sneak it in #427 if it isn't a problem since it's still a css fix.

![Screenshot_20240627_181725_Chrome](https://github.com/naymspace/backpex/assets/279956/6ccc8ebd-29e2-4113-bc34-3d05169fbe86)

**Comment by nedhgx** [comment]
Responsive layout, good experience, not bugs.

**Comment by Flo0807** [comment]
I've also noticed that the topbar covers tooltips:

![image](https://github.com/naymspace/backpex/assets/60519307/f3654d1e-5277-43be-b0d5-93baf8517235)
