### ISSUE TITLE
CSS & JS not loading

### ISSUE THREAD

**Issue by azharmalik3** [naymspace/backpex#430]
Successfully ran the backpex into my project but it seems CSS not loading. Also, showing empty label buttons.

![image](https://github.com/naymspace/backpex/assets/6176136/5b1cacf6-0875-4b2f-abdd-bf7673eb070a)

Also, it shows large icons.

![image](https://github.com/naymspace/backpex/assets/6176136/e84e5a91-8962-4418-a6bd-0e3fada2e46d)

**Comment by Flo0807** [comment]
Hey, are Tailwind CSS and daisyUI installed correctly?

**Comment by azharmalik3** [comment]
Hi, I installed it using the installation guide and I'm not sure if it installed correctly or not.

Do you know how I can verify?

**Comment by fimac** [comment]
I'm having a similar issue. 

<img width="645" alt="Screenshot 2024-07-02 at 11 59 32 am" src="https://github.com/naymspace/backpex/assets/26052576/60ca3f84-bc03-473e-b04d-841f08448b03">

I've been testing out adding Backpex (v0.5.1) into an existing project as we need an admin ui. But the existing project was built as a no html project, as it's just been used for API endpoints until now. So I have had to add in tailwind manually.

I was testing out kaffy and live admin as well, which all rendered ok. It might just be that i've messed something up with the install steps for daisy ui/tailwind config changes.

I'm going to test out the install with a fresh phoenix project and try installing Backpex into that to see if I can work out what i've missed.

**Comment by fimac** [comment]
I tested the install steps in a fresh phoenix project and I'm not having the issue. Just trying to figure out what i'm missing in my initial implementation.

<img width="1440" alt="Screenshot 2024-07-02 at 2 15 17 pm" src="https://github.com/naymspace/backpex/assets/26052576/61092653-6f19-4cfa-9166-6a633b8ccd7c">

**Comment by fimac** [comment]
My issue was due to missing this in the :browser pipeline in `router.ex`.

` plug :put_root_layout, html: {YourAppWeb.Layouts, :root}`

Adding that in, and my UI displays ok now.

<img width="1439" alt="Screenshot 2024-07-02 at 4 10 53 pm" src="https://github.com/naymspace/backpex/assets/26052576/d3078b20-b3a1-48fc-aa76-79d672726276">

I noticed the below error in the console in my browser, if you see that, maybe the above will fix your issue.

<img width="1440" alt="Screenshot 2024-07-02 at 4 11 39 pm" src="https://github.com/naymspace/backpex/assets/26052576/2d46ebca-695b-4c56-a8dc-adbbe18f59a8">

**Comment by azharmalik3** [comment]
Yes, I noticed this and added this line in the router it starts loading layouts but still does not load CSS and JS files.

![image](https://github.com/naymspace/backpex/assets/6176136/a4748b91-1400-4fa2-82f1-b4c8559b69a1)

**Comment by fimac** [comment]
Does your static_paths function in YourAppWeb have assets included?

`def static_paths, do: ~w(assets fonts images favicon.ico robots.txt)`

**Comment by azharmalik3** [comment]
Yes, I added `assets` in the static_paths in my AppWeb. 

![image](https://github.com/naymspace/backpex/assets/6176136/b98a228b-759a-4420-b5c2-6e757bf0b550)

**Comment by azharmalik3** [comment]
Thanks, The Problem is resolved.

I missed some configuration in the `dev.ex` for `tailwind` and  `esbuild`.
